[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
barust = { path = "../barust" }
cairo-rs = { version = "0.15.12", features = ["xcb", "png"] }
chan = "0.1.23"
derive_more = "0.99.17"
env_logger = "0.9.0"
