[package]
name = "barust"
version = "0.3.0"
edition = "2021"
description = "A X11 status bar"
repository = "https://github.com/fiorematteo/barust"
readme = "README.md"
keywords = ["x11", "status", "bar"]
categories = ["gui"]
license = "MIT"

[lib]
name = "barust"

[dependencies]
async-trait = "0.1.71"
cairo-rs = { version = "0.15.12", features = ["xcb"] }
chrono = "0.4.22"
iwlib = "0.1.0"
log = "0.4.17"
pango = "0.15.10"
pangocairo = "0.15.1"
psutil = "3.2.2"
thiserror = "1.0.37"
tokio = { version = "1.29.1", features = ["full"] }
xcb = "1.3.0"
async-channel = "1.9.0"
futures-util = "0.3.28"
signal-hook = "0.3.17"
libnotify = "1.0.3"
libpulse-binding = "2.28.1"
pulsectl-rs = "0.3.2"
pyo3 = { version = "0.19.0", features = ["auto-initialize"] }
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }

[dev-dependencies] 
cairo-rs = { version = "0.15.12", features = ["xcb", "png"] }
console-subscriber = "0.2.0"
log = "0.4.17"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
pyo3 = { version = "0.19.0", features = ["auto-initialize"] }
simple-logging = "2.0.2"

[[example]]
name = "barust"
path = "example/main.rs"
