[package]
name = "barust"
version = "0.3.0"
edition = "2021"
description = "A X11 status bar"
repository = "https://github.com/fiorematteo/barust"
readme = "README.md"
keywords = ["x11", "status", "bar"]
categories = ["gui"]
license = "MIT"

[lib]
name = "barust"

[dependencies]
async-trait = "0.1.71"
cairo-rs = { version = "0.15.12", features = ["xcb"] }
chrono = { version = "0.4.22", optional = true }
iwlib = { version = "0.1.0", optional = true }
log = "0.4.17"
pango = "0.15.10"
pangocairo = "0.15.1"
psutil = { version = "3.2.2", optional = true }
thiserror = "1.0.37"
tokio = { version = "1.29.1", features = ["full"] }
xcb = "1.3.0"
async-channel = "1.9.0"
futures-util = "0.3.28"
signal-hook = "0.3.17"
libnotify = "1.0.3"
libpulse-binding = { version = "2.28.1", optional = true }
pulsectl-rs = {version = "0.3.2", optional = true }
pyo3 = { version = "0.19.0", features = ["auto-initialize"] }
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
ipgeolocate = { version = "0.3.6", optional = true }
open-meteo-api = { version = "0.1.3", optional = true }
public-ip = { version = "0.2.2", optional = true }

[dev-dependencies]
cairo-rs = { version = "0.15.12", features = ["xcb", "png"] }
console-subscriber = "0.2.0"
log = "0.4.17"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
pyo3 = { version = "0.19.0", features = ["auto-initialize"] }
simple-logging = "2.0.2"

[[example]]
name = "barust"
path = "example/main.rs"

[features]
default = ["all"]
all = ["clock", "cpu", "disk", "memory", "psutil", "temp", "pulseaudio", "wlan", "openmeteo"]
clock = ["dep:chrono"]
cpu = ["dep:psutil"]
disk = ["dep:psutil"]
memory = ["dep:psutil"]
psutil = ["dep:psutil"]
temp = ["dep:psutil"]
pulseaudio = ["dep:libpulse-binding", "dep:pulsectl-rs"]
wlan = ["dep:iwlib"]
openmeteo = ["dep:open-meteo-api", "dep:ipgeolocate", "dep:public-ip"]
