[workspace]
members = [
    "core",
    "widgets",
    "example",
    "utils"
]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1.71"
cairo-rs = { version = "0.15.12", features = ["xcb"] }
chrono = "0.4.22"
iwlib = "0.1.0"
log = "0.4.17"
pango = "0.15.10"
pangocairo = "0.15.1"
psutil = "3.2.2"
thiserror = "1.0.37"
tokio = { version = "1.29.1", features = ["full"] }
xcb = { git = "https://github.com/rust-x-bindings/rust-xcb", rev = "dbdaa01" }
async-channel = "1.9.0"
